services:
  - type: web
    name: legion-website-classic
    env: static
    buildCommand: echo "Static site - no build required"
    staticPublishPath: .
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
