services:
  - type: web
    name: legion-website-classic
    env: static
    buildCommand: cp index.html dist/ && cp style.css dist/ && cp script.js dist/
    staticPublishPath: ./dist
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
