services:
  - type: web
    name: legion-website-final
    env: static
    rootDir: .
    buildCommand: npm run build
    publishPath: dist
    headers:
      - path: /*
        name: Cache-Control
        value: "public, max-age=3600"
